name: keybored.fr
description:
author:
author_email:
host: localhost
port: 4000
url: http://www.keybored.fr/
baseurl: 

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

exclude: 
- assets/sass
- README.md

keep_files:
- styles.scss
