name: keybored.fr
description:
author:
author_email:
host: localhost
port: 4000
url: http://www.keybored.fr/
baseurl: 

#highlighter: pygments

exclude: 
- assets/sass
- README.md

keep_files:
- styles.scss
